# can only be run interactively
[ -z "$PS1" ] && return

# get all the needed configurations (i.e. path to this repo etc.)
source ~/.dotfiles_config

source ~/.bashrc

# add bash-completion and git-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

export PATH="/home/teng/repos/darknet/:$PATH"

VERSION=v12.16.2
DISTRO=linux-x64
export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH
