
# get the right `readlink` that can use the -f option
if [ -n $OS ]; then
    if [ "$(uname -s)" = "Darwin" ]; then
        # on OSX
        export OS="MacOS"
    else
        # on Linux
        export OS="$(uname -s)"
    fi
fi

if [ $OS = "MacOS" ]; then
    if [ -n "$(which greadlink)" ]; then
        READLINK_CMD=greadlink
    else
        echo -n "cannot find greadlink, please install coreutils on OSX"
        return
    fi
else
    READLINK_CMD=readlink
fi



# source all the bash-related dotfiles

# DOTFILES_DIR is exported in ~/.dotfiles_config which is sourced upon login in .bash_profile

if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR/system/sources" ]; then
    BASH_CONFIG_DIR="$DOTFILES_DIR/system/sources"

    for BASH_CONFIG_FILE in `find "$BASH_CONFIG_DIR"`; do
        [ -f "$BASH_CONFIG_FILE" ] && source "$($READLINK_CMD -f $BASH_CONFIG_FILE)"
        # or just `source "$BASH_CONFIG_FILE"`
        # maybe no need to use readlink
    done
fi

. /Users/tenglong/code/mine/dotfiles/tools/z/z.sh
. /Users/tenglong/code/mine/dotfiles/system/git-completion.bash

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# braze local dev stuff
export PATH="$(brew --prefix qt@5.5)/bin:$PATH"
