
# get the right `readlink` that can use the -f option
if [ "$(uname -s)" = "Darwin" ]; then
    # on OSX
    OS="MacOS"
    if [ -n "$(which greadlink)" ]; then
        READLINK_CMD=greadlink
    else
        echo -n "cannot find greadlink, please install coreutils on OSX"
        return
    fi
else
    # on Linux
    OS="$(uname -s)"
    READLINK_CMD=readlink
fi

# source all the bash-related dotfiles

# DOTFILES_DIR is exported in ~/.dotfiles_config which is sourced upon login in .bash_profile

if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR/system/sources" ]; then
    BASH_CONFIG_DIR="$DOTFILES_DIR/system/sources"

    for BASH_CONFIG_FILE in `find "$BASH_CONFIG_DIR"`; do
        [ -f "$BASH_CONFIG_FILE" ] && source "$($READLINK_CMD -f $BASH_CONFIG_FILE)"
        # or just `source "$BASH_CONFIG_FILE"`
        # maybe no need to use readlink
    done
fi
