# can only be run interactively
[ -z "$PS1" ] && return

# get all the needed configurations (i.e. path to this repo etc.)
source ~/.dotfiles_config

source ~/.bashrc

# add bash-completion and git-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# SPARK_HOME=~/Code/usr/spark-2.0.1-bin-hadoop2.7
# SCALA_HOME=~/Code/usr/scala-2.12.0
export PATH="/usr/local/opt/scala@2.11/bin:$PATH"
